---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuzhenyang.
--- DateTime: 2020-06-16 19:01
---

local function newObject(o, class)
    class.__index = class
    return setmetatable(o, class)
end

local s_vsh = [[
attribute vec2 vPosition;
varying vec2 uv;
void main()
{
    gl_Position = vec4(vPosition, 0.0, 1.0);
    //An opportunism code. Do not use it unless you know what it means.
    uv = (vPosition.xy + 1.0) / 2.0;
}
]]

local s_fsh = [[
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

uniform sampler2D inputImageTexture;

uniform float fov;
uniform int fovDir;

uniform vec2 fboSize;
uniform vec2 center;

varying vec2 uv;

const float PI = 3.1415926;

float getF(float h, float fov)
{
    //计算焦距
    return (h / 2.0) / (tan(fov / 2.0));
}

void main()
{
    float dis = distance(uv * fboSize, center);

    float f = getF(fboSize.x, fov / 180.0 * PI);   //焦距
    if (fovDir == 0)
    {
        f = getF(fboSize.x, fov / 180.0 * PI);
    }
    else if (fovDir == 1)
    {
        f = getF(fboSize.y, fov / 180.0 * PI);
    }
    else if (fovDir == 2)
    {
        f = getF(distance(vec2(0.0), fboSize), fov / 180.0 * PI);
    }

    float offset_x = uv.x - center.x / fboSize.x;
    float offset_y = uv.y - center.y / fboSize.y;

    if (fov > 0.0)
    {
        float theta = atan(dis, f);
        float offset = f * sin(theta);
        offset_x = offset * abs(uv.x * fboSize.x - center.x) / dis;
        offset_y = offset * abs(uv.y * fboSize.y - center.y) / dis;

        if (uv.x < center.x / fboSize.x) {
            offset_x = -1. * offset_x;
        }
        if (uv.y < center.y / fboSize.y) {
            offset_y = -1. * offset_y;
        }

        offset_x = offset_x / fboSize.x;
        offset_y = offset_y / fboSize.y;
    }
    else if (fov < 0.0)
    {
        float theta = asin(dis / -f);
        float offset = -f * tan(theta) / cos(theta);
        offset_x = offset * abs(uv.x * fboSize.x - center.x) / dis;
        offset_y = offset * abs(uv.y * fboSize.y - center.y) / dis;

        if (uv.x < center.x / fboSize.x) {
            offset_x = -1. * offset_x;
        }
        if (uv.y < center.y / fboSize.y) {
            offset_y = -1. * offset_y;
        }


        offset_x = offset_x / fboSize.x;
        offset_y = offset_y / fboSize.y;
    }

    vec2 nUv = center / fboSize + vec2(offset_x, offset_y);
    vec2 lt = step(vec2(0.0, 0.0), nUv);
    vec2 rb = step(nUv, vec2(1.0, 1.0));
    gl_FragColor = mix(vec4(0.0), texture2D(inputImageTexture, nUv), step(2.0, dot(lt, rb)));
}
]]

LensDistortion2 = {}

function LensDistortion2:matchWithId(effectId)
    return 'KFM KSkr LensDistortion2' == effectId
end

function LensDistortion2.createWithId(effectId)
    if not LensDistortion2:matchWithId(effectId) then
        return nil
    end
    local o = {
        program = {},
        vertexBuffer = 0
    }
    o = newObject(o, LensDistortion2)
    o:init()
    return o;
end

function LensDistortion2:init()
    local buffer = {}
    glGenBuffers(1, buffer)
    self.vertexBuffer=buffer[1]

    local vertexBufferData = CGE.FloatBuffer:alloc(8)
    vertexBufferData:put(8, { -1, -1, 1, -1, -1, 1, 1, 1}, 0)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glBufferData(GL_ARRAY_BUFFER, 8, vertexBufferData, GL_STATIC_DRAW)

    self.program = CGE.ProgramObject()
    self.program:bindAttribLocation("vPosition", 0)
    self.program:initWithShaderStrings(s_vsh, s_fsh)
end

function LensDistortion2:onDestroy()
    glDeleteBuffers(1, {self.vertexBuffer})
end

function LensDistortion2:valueType(index)
    if index == 1 then
        --fov
        return FM.AEValueType_OneDFloat
    elseif index == 2 then
        --center
        return FM.AEValueType_TwoD
    elseif index == 3 then
        --fov dir
        return FM.AEValueType_OneDInt
    end
end

function LensDistortion2:updateValue(index, val1, val2, val3)
    self.program:bind()
    if index == 1 then
        --fov
        self.program:sendUniformf("fov", val1)
    elseif index == 2 then
        -- center
        self.program:sendUniformf("center", val1, val2)
    elseif index == 3 then
        -- fov dir
        self.program:sendUniformi("fovDir", (val1 - 1))
    end
end

function LensDistortion2:resize(width, height)
    self.program:bind()
    self.program:sendUniformf("fboSize", width, height)
end

function LensDistortion2:render(outFBO, inputTex)
    glBindFramebuffer(GL_FRAMEBUFFER, outFBO)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glEnableVertexAttribArray(0)
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, 0)
    glActiveTexture(GL_TEXTURE0)
    glBindTexture(GL_TEXTURE_2D, inputTex)
    self.program:bind()
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)
end
