---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tobeyoung.
--- DateTime: 2019-08-29 14:09
---

local function newObject(o, class)
    class.__index = class
    return setmetatable(o, class)
end

local s_vsh = [[
attribute vec2 vPosition;
varying vec2 textureCoordinate;
void main()
{
    gl_Position = vec4(vPosition, 0.0, 1.0);
    //An opportunism code. Do not use it unless you know what it means.
    textureCoordinate = (vPosition.xy + 1.0) / 2.0;
}
]]

local s_fsh = [[
    #ifdef GL_FRAGMENT_PRECISION_HIGH
    precision highp float;
    #else
    precision mediump float;
    #endif
     const float PI = 3.1415926535898;
     uniform sampler2D inputImageTexture;
     uniform vec2  _mainTexSize;
     uniform vec2  _center;
     uniform float _size;
     uniform float _mirroringType;
     uniform float _rotateAngle;
     uniform float _floatCenter;

     varying vec2 textureCoordinate;

     float SignMirror(float x, float halfPeriod)
     {
         float p = halfPeriod + halfPeriod;
         float xdivp = x/p;
         return p * (xdivp - floor(xdivp + 0.5) );
     }

     float Mirror(float x, float halfPeriod)
     {
         float p = halfPeriod + halfPeriod;
         float xdivp = x / p;
         return p * abs(xdivp - floor(xdivp + 0.5) );
     }
     //x >= 0 is positive, x < 0 is negative
     float Sign(float x)
     {
         return sign(step(0.0, x) - 0.5);
     }

    vec2 Kaleida(in vec2 uv)
    {
        vec2 center =_center;//vec2(_center.x, _mainTexSize.y - _center.y);
        vec2 mirrorCenter = mix(_mainTexSize * 0.5, center, _floatCenter );
        float size = min(_mainTexSize.x, _mainTexSize.y) * 0.5 * _size / 100.0;

        vec2 dir = uv - mirrorCenter;
        vec2 mirrorDir = vec2(Mirror(dir.x, size), Mirror(dir.y, size) );
        dir.x = SignMirror(dir.x, size);
        dir.y = SignMirror(dir.y, size);
        vec2 dirSign = vec2(Sign(dir.x), Sign(dir.y) );
        float theta = 0.0;
        float r = length(dir);
        float rotateAngle = radians(_rotateAngle);
        vec2 xy;

        if(_mirroringType == 1.0){
            //Unfold
            theta = atan(mirrorDir.y, mirrorDir.x);
            theta += rotateAngle;
            xy = vec2(-(cos(theta)), -(sin(theta)) ) * r;
        }

        if(_mirroringType == 2.0){
            //Wheel
            float swap =1.0 - dirSign.x * dirSign.y * 0.5 - 0.5;
            dir = mix(mirrorDir, vec2(mirrorDir.x, mirrorDir.y), swap);
            theta = atan(dir.y, dir.x);
            //odd or even Quadrant : first quadrant number is 1.
            theta += rotateAngle * mix(1.0, -1.0, swap);
            float u = (cos(theta));
            float v = (sin(theta));
            xy = vec2(-mix(u, v, swap), -mix(v, u, swap) ) * r;
        }

        if(_mirroringType == 3.0){
            //Fish Head
            theta = atan(mirrorDir.y, mirrorDir.x);
            float swap =-dirSign.x * 0.5 + 0.5;
            theta += rotateAngle * dirSign.x;
            float u = (cos(theta));
            float v = (sin(theta));
            xy = vec2(-mix(u, v, swap), -mix(v, u, swap) ) * r;
        }

        if(_mirroringType == 4.0){
            //Can meas
            theta = atan(mirrorDir.y, mirrorDir.x);
            float swap = 0.5 - dirSign.y * 0.5;
            theta += rotateAngle * dirSign.y;
            float u = (cos(theta));
            float v = (sin(theta));
            xy = vec2(-mix(u, v, swap), -mix(v, u, swap) ) * r;
        }

        if(_mirroringType == 5.0){
            //Flip flop
            float swap = 0.5 - dirSign.y * 0.5;
            mirrorDir.y = mix(mirrorDir.y, size - mirrorDir.y, swap);
            theta = atan(mirrorDir.y, mirrorDir.x);
            r = length(mirrorDir);
            theta += rotateAngle;
            float u = (cos(theta));
            float v = (sin(theta));
            xy = vec2(-u, -v) * r;
        }

        if(_mirroringType == 6.0 || _mirroringType == 9.0){
            //6:flower 9: starlish
            theta = atan(mirrorDir.y, mirrorDir.x);
            //Triangle wave function
            if(_mirroringType == 6.0)
            {
                theta = Mirror(theta, PI * 0.25);
            }
            else
            {
                theta = Mirror(theta, PI * 0.125);
            }
            theta -= rotateAngle;
            xy = vec2(-(sin(theta)), -(cos(theta)) ) * r;
        }

        if(_mirroringType == 7.0){
            //Dia cross
            theta = atan(-dir.y, dir.x);
            theta = Mirror(theta - PI*0.25, PI * 0.5) + PI*0.25;
            theta -= rotateAngle;
            xy = vec2(cos(theta), -sin(theta)) * r;
        }

        if(_mirroringType == 8.0){
            //flipper
            float swap =0.5 - dirSign.x * dirSign.y * 0.5;
            mirrorDir.x = mix(mirrorDir.x, size - mirrorDir.x, swap);
            theta = atan(mirrorDir.y, mirrorDir.x);
            r = length(mirrorDir);
            theta += rotateAngle;
            xy = vec2(-(cos(theta)), -(sin(theta))) * r;
        }
        vec2 res = center + xy;
        //normalize res value
        res.x = Mirror(res.x, _mainTexSize.x);
        res.y = Mirror(res.y, _mainTexSize.y);
        return res / _mainTexSize;
    }

     void main()
     {
         vec2 uv =textureCoordinate;
         gl_FragColor = texture2D(inputImageTexture, Kaleida(uv * _mainTexSize) );
     }
]]

CCKaleida={}

function CCKaleida:matchWithId(effectId)
    return 'CC Kaleida' == effectId
end

function CCKaleida.createWithId(effectId)
    if not CCKaleida:matchWithId(effectId) then
        return nil
    end
    local o = {
        program = {},
        vertexBuffer = 0
    }
    o = newObject(o, CCKaleida)
    o:init()
    return o;
end

function CCKaleida:init()
    local buffer = {}
    glGenBuffers(1, buffer)
    self.vertexBuffer=buffer[1]

    local vertexBufferData = CGE.FloatBuffer:alloc(8)
    vertexBufferData:put(8, { -1, -1, 1, -1, -1, 1, 1, 1}, 0)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glBufferData(GL_ARRAY_BUFFER, 8, vertexBufferData, GL_STATIC_DRAW)

    self.program = CGE.ProgramObject()
    self.program:bindAttribLocation("vPosition", 0)
    self.program:initWithShaderStrings(s_vsh, s_fsh)
end

function CCKaleida:onDestroy()
    glDeleteBuffers(1, {self.vertexBuffer})
end

function CCKaleida:valueType(index)
    if index == 1 then
    --vec2 center
        return FM.AEValueType_TwoD
    elseif index == 2 then
    --size
        return FM.AEValueType_OneDFloat
    elseif index==3 then
    --mirroring type
        return FM.AEValueType_OneDFloat
    elseif index==4 then
    --rotate angle
        return FM.AEValueType_OneDFloat
    elseif index == 5 then
    --float center
        return FM.AEValueType_OneDFloat
    end
end

function CCKaleida:updateValue(index, val1, val2, val3)
    self.program:bind()
    if index == 1 then
        --center
        self.program:sendUniformf("_center", val1, val2)
    elseif index==2 then
        --size
        self.program:sendUniformf("_size", val1)
    elseif index==3 then
        --_mirroringType
        self.program:sendUniformf("_mirroringType", val1)
    elseif index==4 then
        --rotate angle
        self.program:sendUniformf("_rotateAngle", val1)
    elseif index==5 then
        --float center
        self.program:sendUniformf("_floatCenter", val1)
    end

end

function CCKaleida:resize(width, height)
    self.program:bind()
    self.program:sendUniformf("_mainTexSize", width, height)
end

function CCKaleida:render(outFBO, inputTex)
    glBindFramebuffer(GL_FRAMEBUFFER, outFBO)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glEnableVertexAttribArray(0)
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, 0)
    glActiveTexture(GL_TEXTURE0)
    glBindTexture(GL_TEXTURE_2D, inputTex)
    self.program:bind()
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)
end
