---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuzhenyang.
--- DateTime: 2020-06-16 19:01
---

local function newObject(o, class)
    class.__index = class
    return setmetatable(o, class)
end

local s_vsh = [[
attribute vec2 vPosition;
varying vec2 uv;
void main()
{
    gl_Position = vec4(vPosition, 0.0, 1.0);
    //An opportunism code. Do not use it unless you know what it means.
    uv = (vPosition.xy + 1.0) / 2.0;
}
]]

local s_fsh = [[
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

uniform sampler2D inputImageTexture;

uniform vec2 fboSize;
uniform vec2 center1;
uniform float ratio1;
uniform float size;
uniform int blendMode;
uniform int shape;
uniform int link;
uniform float alpha1;
uniform float feather;

varying vec2 uv;

vec2 scale(vec2 srcTex, vec2 center, float ratio)
{
    return (srcTex - center) / ratio + center;
}

vec4 blendNormal(vec4 c2, vec4 c1) {
    vec4 outputColor;
    outputColor.r = c1.r + c2.r * c2.a * (1.0 - c1.a);
    outputColor.g = c1.g + c2.g * c2.a * (1.0 - c1.a);
    outputColor.b = c1.b + c2.b * c2.a * (1.0 - c1.a);
    outputColor.a = c1.a + c2.a * (1.0 - c1.a);
    return outputColor;
}

vec3 blendAdd(vec3 src1, vec3 src2, float alpha)
{
    return src1 + src2 * alpha;
}

vec3 blendMultiply(vec3 src1, vec3 src2, float alpha)
{
    return src1 * (1.0 - alpha) + src1 * src2 * alpha;
}

vec3 blendScreen(vec3 src1, vec3 src2, float alpha)
{
    return src1 + src2 * alpha - src1 * src2 * alpha;
}

vec3 blendOverlay(vec3 src1, vec3 src2, float alpha)
{
    float revAlpha = 1.0 - alpha;
    //ks version.
    vec3 src3 = src2 * 2.0 * alpha;
    src2 = mix((src1 - 1.0) * (alpha - src3) + src1, src1 * src3 + src1 * revAlpha, step(src1, vec3(0.5)));
    return src2;
}

vec3 blendSoftLight(vec3 src1, vec3 src2, float alpha)
{
    return mix(src1, src1 * (alpha * src1 + (2.0 * src2 * (1.0 - src1))) + src1 * (1.0 - alpha), alpha);
}

vec3 blendHardLight(vec3 src1, vec3 src2, float alpha)
{
    vec3 src1x2 = src1 * src2 * alpha * 2.0;
    src2 = mix(src1x2, ((src1 * alpha + src2 * alpha) * 2.0 - src1x2 - alpha), step(0.5 * alpha, src2 * alpha));
    return src1 * (1.0 - alpha) + src2;
}

vec3 blendColorDodge(vec3 src1, vec3 src2, float alpha)
{
    src2 = clamp(src2 * alpha, 0.0, alpha - 0.001);
    return mix(src1, min(alpha*src1 / (alpha - src2), 1.0), alpha);
}

vec3 blendColorBurn(vec3 src1, vec3 src2, float alpha)
{
    /// plus 0.001 to avoid dividing by float zero
    return mix(src1, 1.0 - min((1.0 - src1) / (src2 + 0.001), 1.0), alpha);
}

vec3 blendDarken(vec3 src1, vec3 src2, float alpha)
{
    return src1*(1.0 - alpha) + min(src1*alpha, src2 * alpha);
}

vec3 blendLighten(vec3 src1, vec3 src2, float alpha)
{
    return src1*(1.0 - alpha) + max(src1*alpha, src2 * alpha);
}

vec3 blendDifference(vec3 src1, vec3 src2, float alpha)
{
    return src1*(1.0 - alpha) + abs(src1*alpha - src2 * alpha);
}

vec3 blendExclude(vec3 src1, vec3 src2, float alpha)
{
    return src1*(1.0 - alpha) + (alpha*src1 + src2 * alpha - src1*src2*alpha*2.0);
}

vec3 RGB2HSL(vec3 src)
{
    float maxc = max(max(src.r, src.g), src.b);
    float minc = min(min(src.r, src.g), src.b);
    float L = (maxc + minc) / 2.0;
    if(maxc == minc)
        return vec3(0.0, 0.0, L);
    float H, S;

    if(L < 0.5)
        S = (maxc - minc) / (maxc + minc);
    else
        S = (maxc - minc) / (2.0 - maxc - minc);

    if(maxc == src.r)
        H = (src.g - src.b) / (maxc - minc);
    else if(maxc == src.g)
        H = 2.0 + (src.b - src.r) / (maxc - minc);
    else
        H = 4.0 + (src.r - src.g) / (maxc - minc);
    H *= 60.0;
    if(H < 0.0) H += 360.0;
    return vec3(H / 360.0, S, L); // H(0~1), S(0~1), L(0~1)
}

vec3 HSL2RGB(vec3 src) // H, S, L
{
    if(src.y <= 0.0)
        return vec3(src.z, src.z, src.z);
    float q = (src.z < 0.5) ? src.z * (1.0 + src.y) : (src.z + src.y - (src.y * src.z));
    float p = 2.0 * src.z - q;

    vec3 dst = vec3(src.x + 0.333, src.x, src.x - 0.333);

    if(dst.r < 0.0) dst.r += 1.0;
    else if(dst.r > 1.0) dst.r -= 1.0;

    if(dst.g < 0.0) dst.g += 1.0;
    else if(dst.g > 1.0) dst.g -= 1.0;

    if(dst.b < 0.0) dst.b += 1.0;
    else if(dst.b > 1.0) dst.b -= 1.0;

    if(dst.r < 1.0 / 6.0)
        dst.r = p + (q - p) * 6.0 * dst.r;
    else if(dst.r < 0.5)
        dst.r = q;
    else if(dst.r < 2.0 / 3.0)
        dst.r = p + (q - p) * ((2.0 / 3.0) - dst.r) * 6.0;
    else dst.r = p;

    if(dst.g < 1.0 / 6.0)
        dst.g = p + (q - p) * 6.0 * dst.g;
    else if(dst.g < 0.5)
        dst.g = q;
    else if(dst.g < 2.0 / 3.0)
        dst.g = p + (q - p) * ((2.0 / 3.0) - dst.g) * 6.0;
    else dst.g = p;

    if(dst.b < 1.0 / 6.0)
        dst.b = p + (q - p) * 6.0 * dst.b;
    else if(dst.b < 0.5)
        dst.b = q;
    else if(dst.b < 2.0 / 3.0)
        dst.b = p + (q - p) * ((2.0 / 3.0) - dst.b) * 6.0;
    else dst.b = p;

    return dst;
}


vec3 blendHue(vec3 src1, vec3 src2, float alpha)
{
    vec3 hsl1 = RGB2HSL(src1);
    vec3 hsl2 = RGB2HSL(src2 * alpha);
    vec3 dst = HSL2RGB(vec3(hsl2.r, hsl1.gb));

    return mix(src1, dst, alpha);
}

vec3 blendSaturation(vec3 src1, vec3 src2, float alpha)
{
    vec3 hsl1 = RGB2HSL(src1);
    vec3 hsl2 = RGB2HSL(src2 * alpha);
    vec3 dst = HSL2RGB(vec3(hsl1.r, hsl2.g, hsl1.b));

    return mix(src1, dst, alpha);
}

float getLumValue(vec3 src)
{
    return 0.299 * src.r + 0.587 * src.g + 0.114 * src.b;
}

vec3 blendColor(vec3 src1, vec3 src2, float alpha)
{
    return src1*(1.0 - alpha) +  getLumValue(src1*alpha) - getLumValue(src2 * alpha) + src2 * alpha;
}

vec3 blendLuminosity(vec3 src1, vec3 src2, float alpha)
{
    return mix(src1, getLumValue(src2 * alpha) - getLumValue(src1) + src1, alpha);
}

void main(){
    vec3 blend = vec3(0.0);
    float blendAlpha = 0.0;

    vec3 target = texture2D(inputImageTexture, uv).rgb;
    float targetAlpha = texture2D(inputImageTexture, uv).a;

    float limit = 0.0;

    if (link == 0)
    {
        limit = size;
    }
    else if (link == 1)
    {
        limit = size * ratio1 / 100.0;
    }

    if (shape == 0)
    {
        if (distance(uv * fboSize, center1) < limit)
        {
            blend = texture2D(inputImageTexture, scale(uv, center1 / fboSize, ratio1 / 100.0)).rgb;
            blendAlpha = targetAlpha;
        }

    }
    else if (shape == 1)
    {
        if (abs((uv * fboSize - center1).x) < limit && abs((uv * fboSize - center1).y) < limit)
        {
            blend = texture2D(inputImageTexture, scale(uv, center1 / fboSize, ratio1 / 100.0)).rgb;
            blendAlpha = targetAlpha;
        }
    }

    if (feather > 0.0)
    {
        if (blendMode == 0)
        {
            if (distance(uv * fboSize, center1) < limit * sqrt(2.0) - feather)
            {
                blend = texture2D(inputImageTexture, scale(uv, center1 / fboSize, ratio1 / 100.0)).rgb;
                blendAlpha = targetAlpha;
            }
            else if (distance(uv * fboSize, center1) > limit * sqrt(2.0) + feather)
            {

            }
            else 
            {
                float k = (distance(uv * fboSize, center1) - (limit * sqrt(2.0) - feather)) / (2.0 * feather);
                blend = texture2D(inputImageTexture, scale(uv, center1 / fboSize, ratio1 / 100.0)).rgb * (1.0 - k);
                blendAlpha = targetAlpha * (1.0 - k);
            }
        }
        else if (blendMode == 1)
        {
            if (distance(uv * fboSize, center1) < limit * sqrt(2.0) - feather)
            {
                blend = texture2D(inputImageTexture, scale(uv, center1 / fboSize, ratio1 / 100.0)).rgb;
                blendAlpha = targetAlpha;
            }
            else if (distance(uv * fboSize, center1) > limit * sqrt(2.0) + feather)
            {

            }
            else 
            {
                float k = (distance(uv * fboSize, center1) - (limit * sqrt(2.0) - feather)) / (2.0 * feather);
                blend = mix(texture2D(inputImageTexture, scale(uv, center1 / fboSize, ratio1 / 100.0)).rgb, texture2D(inputImageTexture, uv).rgb, k);
                blendAlpha = targetAlpha;
            }
        }
        else
        {
            if (distance(uv * fboSize, center1) < limit * sqrt(2.0) - feather)
            {
                blend = texture2D(inputImageTexture, scale(uv, center1 / fboSize, ratio1 / 100.0)).rgb;
                blendAlpha = targetAlpha;
            }
            else if (distance(uv * fboSize, center1) > limit * sqrt(2.0) + feather)
            {

            }
            else 
            {
                float k = (distance(uv * fboSize, center1) - (limit * sqrt(2.0) - feather)) / (2.0 * feather);
                blend = texture2D(inputImageTexture, scale(uv, center1 / fboSize, ratio1 / 100.0)).rgb;
                blendAlpha = targetAlpha * (1.0 - k);
            }
        }
    }

    if (blendMode == 0)
    {
        gl_FragColor = vec4(blend, blendAlpha) * alpha1;
    }
    else if (blendMode == 1)
    {
        gl_FragColor = blendNormal(vec4(target, targetAlpha), vec4(blend, blendAlpha) * alpha1);
    }
    else if (blendMode == 2)
    {
        gl_FragColor = vec4(blendAdd(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 3)
    {
        gl_FragColor = vec4(blendMultiply(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 4)
    {
        gl_FragColor = vec4(blendScreen(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 5)
    {
        gl_FragColor = vec4(blendOverlay(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 6)
    {
        gl_FragColor = vec4(blendSoftLight(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 7)
    {
        gl_FragColor = vec4(blendHardLight(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 8)
    {
        gl_FragColor = vec4(blendColorDodge(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 9)
    {
        gl_FragColor = vec4(blendColorBurn(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 10)
    {
        gl_FragColor = vec4(blendDarken(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 11)
    {
        gl_FragColor = vec4(blendLighten(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 12)
    {
        gl_FragColor = vec4(blendDifference(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 13)
    {
        gl_FragColor = vec4(blendExclude(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 14)
    {
        gl_FragColor = vec4(blendHue(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 15)
    {
        gl_FragColor = vec4(blendSaturation(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 16)
    {
        gl_FragColor = vec4(blendColor(target, blend, blendAlpha * alpha1), targetAlpha);
    }
    else if (blendMode == 17)
    {
        gl_FragColor = vec4(blendLuminosity(target, blend, blendAlpha * alpha1), targetAlpha);
    }
}
]]

Enlargement = {}

function Enlargement:matchWithId(effectId)
    return 'KFM KSkr Enlargement' == effectId
end

function Enlargement.createWithId(effectId)
    if not Enlargement:matchWithId(effectId) then
        return nil
    end
    local o = {
        program = {},
        vertexBuffer = 0
    }
    o = newObject(o, Enlargement)
    o:init()
    return o;
end

function Enlargement:init()
    local buffer = {}
    glGenBuffers(1, buffer)
    self.vertexBuffer=buffer[1]

    local vertexBufferData = CGE.FloatBuffer:alloc(8)
    vertexBufferData:put(8, { -1, -1, 1, -1, -1, 1, 1, 1}, 0)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glBufferData(GL_ARRAY_BUFFER, 8, vertexBufferData, GL_STATIC_DRAW)

    self.program = CGE.ProgramObject()
    self.program:bindAttribLocation("vPosition", 0)
    self.program:initWithShaderStrings(s_vsh, s_fsh)
end

function Enlargement:onDestroy()
    glDeleteBuffers(1, {self.vertexBuffer})
end

function Enlargement:valueType(index)
    if index == 1 then
        --shape
        return FM.AEValueType_OneDInt
    elseif index == 2 then
        --center
        return FM.AEValueType_TwoD
    elseif index == 3 then
        --ratio
        return FM.AEValueType_OneDFloat
    elseif index == 4 then
        --link
        return FM.AEValueType_OneDInt
    elseif index == 5 then
        --size
        return FM.AEValueType_OneDFloat
    elseif index == 6 then
        --feather
        return FM.AEValueType_OneDFloat
    elseif index == 7 then
        --alpha
        return FM.AEValueType_OneDFloat
    elseif index == 8 then
        --blendMode
        return FM.AEValueType_OneDInt
    end
end

function Enlargement:updateValue(index, val1, val2, val3)
    self.program:bind()
    if index == 1 then
        --shape
        self.program:sendUniformi("shape", (val1 - 1))
    elseif index == 2 then
        -- center
        self.program:sendUniformf("center1", val1, val2)
    elseif index == 3 then
        -- ratio
        self.program:sendUniformf("ratio1", val1)
    elseif index == 4 then
        -- link
        self.program:sendUniformi("link", (val1 - 1))
    elseif index == 5 then
        -- size
        self.program:sendUniformf("size", val1)
    elseif index == 6 then
        -- feather
        self.program:sendUniformf("feather", val1)
    elseif index == 7 then
        -- alpha
        self.program:sendUniformf("alpha1", val1)
    elseif index == 8 then
        -- blendMode
        self.program:sendUniformi("blendMode", (val1 - 1))
    end
end

function Enlargement:resize(width, height)
    self.program:bind()
    self.program:sendUniformf("fboSize", width, height)
end

function Enlargement:render(outFBO, inputTex)
    glBindFramebuffer(GL_FRAMEBUFFER, outFBO)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glEnableVertexAttribArray(0)
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, 0)
    glActiveTexture(GL_TEXTURE0)
    glBindTexture(GL_TEXTURE_2D, inputTex)
    self.program:bind()
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)
end
