---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuzhenyang.
--- DateTime: 2020-06-16 19:01
---

require('script/bowknot/vec2')
require('script/bowknot/mat4')

local function newObject(o, class)
    class.__index = class
    return setmetatable(o, class)
end

local s_vsh = [[
attribute vec2 vPosition;
varying vec2 vUV0;

uniform float angle;
uniform int dir;
uniform mat4 spriteModelViewProjection;
uniform vec2 canvasSize;

void main()
{
    vUV0 = (vPosition.xy + 1.0) / 2.0;
    vec2 texSize = canvasSize / 2.0;
    vec3 pos = vec3(vPosition * texSize, 0.0);

    vec3 result = pos;

    float k = vUV0.x;
    float r = angle;
    if (dir == 0)
    {
        if (r < 180.0)
        {
            result.y = pos.y * cos(k * r * 3.14 / 180.0);
            result.z = pos.y * sin(k * r * 3.14 / 180.0);
        }
        else
        {
            k = 1.0 - vUV0.x;
            r = 360.0 - r;
            result.y = -pos.y * cos(k * r * 3.14 / 180.0);
            result.z = pos.y * sin(k * r * 3.14 / 180.0);
        }
    }
    else
    {
        if (r < 180.0)
        {
            result.y = pos.y * cos(k * r * 3.14 / 180.0);
            result.z = -pos.y * sin(k * r * 3.14 / 180.0);
        }
        else
        {
            k = 1.0 - vUV0.x;
            r = 360.0 - r;
            result.y = -pos.y * cos(k * r * 3.14 / 180.0);
            result.z = -pos.y * sin(k * r * 3.14 / 180.0);
        }
    }
    gl_Position = spriteModelViewProjection * vec4(result, 1.0);
}
]]

local s_fsh = [[
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

uniform sampler2D inputImageTexture;

varying vec2 vUV0;

void main()
{
    gl_FragColor = texture2D(inputImageTexture, vUV0);
}
]]

Bowknot = {}

function Bowknot:matchWithId(effectId)
    return 'KFM KSkr Bowknot' == effectId
end

function Bowknot.createWithId(effectId)
    if not Bowknot:matchWithId(effectId) then
        return nil
    end
    local o = {
        program = {},
        vertexBuffer = 0,
        meshSize = 0,
        vertexBufferDataForFront = {},
        vertexBufferDataForBack = {},
        type = 0,
        ebo = 0
    }
    o = newObject(o, Bowknot)
    o:init()
    return o;
end

function Bowknot:init()
    local buffer = {}
    glGenBuffers(2, buffer)
    self.vertexBuffer=buffer[1]
    self.ebo = buffer[2]
    local meshVerticesForFront = {}
    local meshVerticesForBack = {}    
    local indices = {}

    local col = 10
    local row = 10
    for j = 0, row, 1 do
        for i = 0, col, 1 do
            table.insert(meshVerticesForBack, -1 + i / (col / 2))
            table.insert(meshVerticesForBack, -1 + j / (row / 2))
        end
    end

    for j = row, 0, -1 do
        for i = col, 0, -1 do
            table.insert(meshVerticesForFront, -1 + i / (col / 2))
            table.insert(meshVerticesForFront, -1 + j / (row / 2))
        end
    end

    for j = 0, row-1, 1 do
        for i = 0, col-1, 1 do
            table.insert(indices, i + (col + 1) * j)
            table.insert(indices, i + (col + 1) * j + 1)
            table.insert(indices, i + (col + 1) * (j + 1))
            table.insert(indices, i + (col + 1) * (j + 1) + 1)
            table.insert(indices, i + (col + 1) * (j + 1))
            table.insert(indices, i + (col + 1) * j + 1)
        end
    end    

    self.indexSize = #indices

    self.meshSize = #meshVerticesForFront

    self.vertexBufferDataForFront = CGE.FloatBuffer:alloc(self.meshSize)
    self.vertexBufferDataForFront:put(self.meshSize, meshVerticesForFront, 0)

    self.vertexBufferDataForBack = CGE.FloatBuffer:alloc(self.meshSize)
    self.vertexBufferDataForBack:put(self.meshSize, meshVerticesForBack, 0)


    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glBufferData(GL_ARRAY_BUFFER, self.meshSize, nil, GL_STREAM_DRAW)

    local indexBuffer = CGE.ShortBuffer:alloc(#indices)
    indexBuffer:put(#indices, indices, 0)

    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, self.ebo)
    glBufferDataS(GL_ELEMENT_ARRAY_BUFFER, #indices, indexBuffer:position(0), GL_STATIC_DRAW)

    self.program = CGE.ProgramObject()
    self.program:bindAttribLocation("vPosition", 0)
    if (self.program:initWithShaderStrings(s_vsh, s_fsh)) then
        self.program:bind()
        self.MVPLoc = self.program:uniformLocation('spriteModelViewProjection')
        self.canvasSizeLoc = self.program:uniformLocation('canvasSize')        
    end
end

function Bowknot:onDestroy()
    glDeleteBuffers(2, {self.vertexBuffer, self.ebo})
end

function Bowknot:valueType(index)
    if index == 1 then
        --strength
        return FM.AEValueType_OneDFloat
    elseif index == 2 then
        return FM.AEValueType_OneDInt
    end
end

function Bowknot:updateValue(index, val1, val2, val3)
    self.program:bind()
    if index == 1 then
        --strength        
        self.program:sendUniformf("angle", val1)
    elseif index == 2 then
        self.type = val1 - 1
        self.program:sendUniformi("dir", (val1 - 1))
    end
end

function Bowknot:resize(width, height)
    local fovy = math.pi / 3
    local proj = makePerspective(fovy, width/height, 0.1, 5000)

    local view = makeLookAt(vec3(0,0,height/(math.tan(fovy/2)*2)),vec3(0,0,0),vec3(0,1,0))

    proj = proj * view
    self.program:bind()

    local proj_numTable = {proj.m00,proj.m01,proj.m02,proj.m03,
                           proj.m10,proj.m11,proj.m12,proj.m13,
                           proj.m20,proj.m21,proj.m22,proj.m23,
                           proj.m30,proj.m31,proj.m32,proj.m33}

    glUniformMatrix4fv(self.MVPLoc, 1, 0, proj_numTable)
    glUniform2f(self.canvasSizeLoc, width, height)
end

function Bowknot:render(outFBO, inputTex)

    glBindFramebuffer(GL_FRAMEBUFFER, outFBO)

    glClearColor(0, 0, 0, 0)
    glClear(GL_COLOR_BUFFER_BIT)

    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    if self.type == 1 then
        glBufferSubData(GL_ARRAY_BUFFER, 0, self.meshSize, self.vertexBufferDataForFront)
    else
        glBufferSubData(GL_ARRAY_BUFFER, 0, self.meshSize, self.vertexBufferDataForBack)        
    end


    glEnableVertexAttribArray(0)
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, 0)

    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, self.ebo)

    glActiveTexture(GL_TEXTURE0)
    glBindTexture(GL_TEXTURE_2D, inputTex)
    self.program:bind()
    glDrawElements(GL_TRIANGLES, self.indexSize, GL_UNSIGNED_SHORT, 0)
    -- glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)
end
