---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tobeyoung.
--- DateTime: 2020-05-16 11:11
---

local function newObject(o, class)
    class.__index = class
    return setmetatable(o, class)
end

local s_vsh = [[
attribute vec2 vPosition;
varying vec2 vUV0;
void main()
{
    gl_Position = vec4(vPosition, 0.0, 1.0);
    //An opportunism code. Do not use it unless you know what it means.
    vUV0 = (vPosition.xy + 1.0) / 2.0;
}
]]

local s_fsh = [[
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

    uniform sampler2D inputImageTexture;
    uniform vec2  uMainTexSize;
    uniform vec2 uCenter;
    uniform float uStrength;
    uniform int uType;

    varying vec2 vUV0;

    vec2 mirror(vec2 tex)
    {
        return vec2(abs(mod(floor(tex.x), 2.0) - (tex.x - floor(tex.x))), 
                    abs(mod(floor(tex.y), 2.0) - (tex.y - floor(tex.y))));
    }

    void main()
    {
        float aspect = uMainTexSize.x / uMainTexSize.y;
        vec2 center = uCenter / uMainTexSize;
        vec2 dir = (vUV0 - center) * 2.0;
        dir.x *= aspect;
        vec2 nDir = normalize(dir) * uStrength;
        nDir = dir + nDir;
        nDir.x = nDir.x / aspect;
        vec2 uv;
        if (uType == 1)
        {
            uv = (nDir + vec2(1.0, 1.0)) * vec2(0.5, 0.5);
        }
        else if (uType == 2)
        {
            uv = mod((nDir + vec2(1.0, 1.0)) * vec2(0.5, 0.5), 1.0);
        }
        else if (uType == 3)
        {
            uv = mirror((nDir + vec2(1.0, 1.0)) * vec2(0.5, 0.5));
        }
        gl_FragColor = texture2D(inputImageTexture, uv);
    }
]]

Inhalation = {}

function Inhalation:matchWithId(effectId)
    return 'KFM KSkr Inhalation' == effectId
end

function Inhalation.createWithId(effectId)
    if not Inhalation:matchWithId(effectId) then
        return nil
    end
    local o = {
        program = {},
        vertexBuffer = 0
    }
    o = newObject(o, Inhalation)
    o:init()
    return o;
end

function Inhalation:init()
    local buffer = {}
    glGenBuffers(1, buffer)
    self.vertexBuffer=buffer[1]

    local vertexBufferData = CGE.FloatBuffer:alloc(8)
    vertexBufferData:put(8, { -1, -1, 1, -1, -1, 1, 1, 1}, 0)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glBufferData(GL_ARRAY_BUFFER, 8, vertexBufferData, GL_STATIC_DRAW)

    self.program = CGE.ProgramObject()
    self.program:bindAttribLocation("vPosition", 0)
    self.program:initWithShaderStrings(s_vsh, s_fsh)
end

function Inhalation:updateTimeAndFrame(time)

end

function Inhalation:onDestroy()
    glDeleteBuffers(1, {self.vertexBuffer})
end

function Inhalation:valueType(index)
    if index == 1 then
        --vec2 center
        return FM.AEValueType_TwoD
    elseif index == 2 then
        --size
        return FM.AEValueType_OneDFloat
    elseif index == 3 then
        --type  
        -- clamp  <--->  1
        -- repeat <--->  2
        -- mirror <--->  3
        return FM.AEValueType_OneDInt
    end
end

function Inhalation:updateValue(index, val1, val2, val3)
    self.program:bind()
    if index == 1 then
        --center
        self.program:sendUniformf("uCenter", val1, val2)
    elseif index == 2 then
        --size
        self.program:sendUniformf("uStrength", val1)
    elseif index == 3 then
        --type  
        -- clamp  <--->  1
        -- repeat <--->  2
        -- mirror <--->  3
        self.program:sendUniformi("uType", val1)          
    end
end

function Inhalation:resize(width, height)
    self.program:bind()
    self.program:sendUniformf("uMainTexSize", width, height)
end

function Inhalation:render(outFBO, inputTex)
    glBindFramebuffer(GL_FRAMEBUFFER, outFBO)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glEnableVertexAttribArray(0)
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, 0)
    glActiveTexture(GL_TEXTURE0)
    glBindTexture(GL_TEXTURE_2D, inputTex)
    self.program:bind()
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)
end
