---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuzhenyang.
--- DateTime: 2020-05-21 16:31
---

local function newObject(o, class)
    class.__index = class
    return setmetatable(o, class)
end

local s_vsh = [[
attribute vec2 vPosition;
varying vec2 vUV0;
void main()
{
    gl_Position = vec4(vPosition, 0.0, 1.0);
    //An opportunism code. Do not use it unless you know what it means.
    vUV0 = (vPosition.xy + 1.0) / 2.0;
}
]]

local s_fsh = [[
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

    uniform sampler2D inputImageTexture;
    uniform vec2  uMainTexSize;
    uniform float uStrength;

    varying vec2 vUV0;

    void main()
    {
        vec2 step = uStrength / uMainTexSize;
        vec3 color = texture2D(inputImageTexture, vUV0 + vec2(-step.x, step.y)).rgb - texture2D(inputImageTexture, vUV0 + vec2(step.x, -step.y)).rgb;
        gl_FragColor = vec4(color + vec3(0.5), 1.0);
    }
]]

Engrave = {}

function Engrave:matchWithId(effectId)
    return 'KFM KSkr Engrave' == effectId
end

function Engrave.createWithId(effectId)
    if not Engrave:matchWithId(effectId) then
        return nil
    end
    local o = {
        program = {},
        vertexBuffer = 0
    }
    o = newObject(o, Engrave)
    o:init()
    return o;
end

function Engrave:init()
    local buffer = {}
    glGenBuffers(1, buffer)
    self.vertexBuffer=buffer[1]

    local vertexBufferData = CGE.FloatBuffer:alloc(8)
    vertexBufferData:put(8, { -1, -1, 1, -1, -1, 1, 1, 1}, 0)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glBufferData(GL_ARRAY_BUFFER, 8, vertexBufferData, GL_STATIC_DRAW)

    self.program = CGE.ProgramObject()
    self.program:bindAttribLocation("vPosition", 0)
    self.program:initWithShaderStrings(s_vsh, s_fsh)
end

function Engrave:updateTimeAndFrame(time)
    
end

function Engrave:onDestroy()
    glDeleteBuffers(1, {self.vertexBuffer})
end

function Engrave:valueType(index)
    if index == 1 then
        --strength
        return FM.AEValueType_OneDFloat
    end
end

function Engrave:updateValue(index, val1, val2, val3)
    self.program:bind()
    if index == 1 then
        --strength        
        self.program:sendUniformf("uStrength", val1)
    end
end

function Engrave:resize(width, height)
    self.program:bind()
    self.program:sendUniformf("uMainTexSize", width, height)
end

function Engrave:render(outFBO, inputTex)
    glBindFramebuffer(GL_FRAMEBUFFER, outFBO)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glEnableVertexAttribArray(0)
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, 0)
    glActiveTexture(GL_TEXTURE0)
    glBindTexture(GL_TEXTURE_2D, inputTex)
    self.program:bind()
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)
end