---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuming.
--- DateTime: 2020-08-05 14:20
---

local function newObject(o, class)
    class.__index = class
    return setmetatable(o, class)
end

local s_vsh = [[
attribute vec2 vPosition;
varying vec2 vUV0;

varying vec2 texCoord[8];
uniform vec2  uMainTexSize;
uniform float uSamplerStepMultiplier;

void main()
{
    gl_Position = vec4(vPosition, 0.0, 1.0);
    //An opportunism code. Do not use it unless you know what it means.
    vUV0 = (vPosition.xy + 1.0) / 2.0;

    vec2 samplerSteps=vec2(uSamplerStepMultiplier/uMainTexSize.x,uSamplerStepMultiplier/uMainTexSize.y);

    texCoord[0] = vUV0 - samplerSteps;
    texCoord[1] = vUV0 + vec2(0, -samplerSteps.y);
    texCoord[2] = vUV0 + vec2(samplerSteps.x, -samplerSteps.y);
    texCoord[3] = vUV0 + vec2(-samplerSteps.x, 0.0);
    texCoord[4] = vUV0 + vec2(samplerSteps.x, 0.0);
    texCoord[5] = vUV0 + vec2(-samplerSteps.x, samplerSteps.y);
    texCoord[6] = vUV0 + vec2(0.0, samplerSteps.y);
    texCoord[7] = vUV0 + samplerSteps;
}
]]

local s_fsh = [[
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

    uniform sampler2D inputImageTexture;
    varying vec2 vUV0;
    
    varying vec2 texCoord[8];
    
    uniform float uIntensity;

   float lum(vec4 v)
   {
       return dot(v.rgb, vec3(0.299, 0.587, 0.114));
   }

   vec4 getMaxValue(vec4 newValue,vec4 originValue)
   {
       return mix(newValue,originValue,step(lum(newValue),lum(originValue)));
   }


    void main()
    {
        vec4 origin = texture2D(inputImageTexture, vUV0);
        vec4 vMax;
        {
            vec4 vTemp;
            vMax=texture2D(inputImageTexture, texCoord[0]);

            vTemp=texture2D(inputImageTexture, texCoord[1]);
            vMax=getMaxValue(vTemp,vMax);

            vTemp=texture2D(inputImageTexture, texCoord[2]);
            vMax=getMaxValue(vTemp,vMax);

            vTemp=texture2D(inputImageTexture, texCoord[3]);
            vMax=getMaxValue(vTemp,vMax);

            vTemp=texture2D(inputImageTexture, texCoord[4]);
            vMax=getMaxValue(vTemp,vMax);

            vTemp=texture2D(inputImageTexture, texCoord[5]);
            vMax=getMaxValue(vTemp,vMax);

            vTemp=texture2D(inputImageTexture, texCoord[6]);
            vMax=getMaxValue(vTemp,vMax);

            vTemp=texture2D(inputImageTexture, texCoord[7]);
            vMax=getMaxValue(vTemp,vMax);

            vMax=getMaxValue(origin,vMax);
        }

        float lumOrigin = lum(origin);
        float lumMax = lum(vMax) + 0.001;
        float blendColor = min(lumOrigin / lumMax, 1.0);
        gl_FragColor = vec4(mix(origin.rgb, vec3(blendColor), uIntensity), origin.a);
    }
]]

Sketch = {}

function Sketch:matchWithId(effectId)
    return 'KFM KSkr Sketch' == effectId
end

function Sketch.createWithId(effectId)
    if not Sketch:matchWithId(effectId) then
        return nil
    end
    local o = {
        program = {},
        vertexBuffer = 0
    }
    o = newObject(o, Sketch)
    o:init()
    return o;
end


function Sketch:init()
    local buffer = {}
    glGenBuffers(1, buffer)
    self.vertexBuffer=buffer[1]

    local vertexBufferData = CGE.FloatBuffer:alloc(8)
    vertexBufferData:put(8, { -1, -1, 1, -1, -1, 1, 1, 1}, 0)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glBufferData(GL_ARRAY_BUFFER, 8, vertexBufferData, GL_STATIC_DRAW)

    self.program = CGE.ProgramObject()
    self.program:bindAttribLocation("vPosition", 0)
    self.program:initWithShaderStrings(s_vsh, s_fsh)
end

function Sketch:onDestroy()
    glDeleteBuffers(1, {self.vertexBuffer})
end

function Sketch:updateTimeAndFrame(time)

end

function Sketch:valueType(index)
    if index == 1 then
        --intensity
        return FM.AEValueType_OneDFloat
    elseif index==2 then
        --samplerStepMultiplier
        return FM.AEValueType_OneDFloat
    end
end

function Sketch:updateValue(index, val1, val2, val3)
    self.program:bind()
    if index == 1 then
        --intensity
        self.program:sendUniformf("uIntensity", val1)
    elseif index==2 then
        --samplerStepMultiplier
        self.program:sendUniformf("uSamplerStepMultiplier", val1)
    end
end

function Sketch:resize(width, height)
    self.program:bind()
    self.program:sendUniformf("uMainTexSize", width, height)
end

function Sketch:render(outFBO, inputTex)
    glBindFramebuffer(GL_FRAMEBUFFER, outFBO)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glEnableVertexAttribArray(0)
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, 0)
    glActiveTexture(GL_TEXTURE0)
    glBindTexture(GL_TEXTURE_2D, inputTex)
    self.program:bind()
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)
end
