---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuzhenyang.
--- DateTime: 2020-06-16 19:01
---

local function newObject(o, class)
    class.__index = class
    return setmetatable(o, class)
end

local s_vsh = [[
attribute vec2 vPosition;
varying vec2 uv;
void main()
{
    gl_Position = vec4(vPosition, 0.0, 1.0);
    //An opportunism code. Do not use it unless you know what it means.
    uv = (vPosition.xy + 1.0) / 2.0;
}
]]

local s_fsh = [[
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

uniform sampler2D inputImageTexture;
uniform vec2  uMainTexSize;
uniform int flip;

uniform vec2 V3;    //topLeft
uniform vec2 V2;    //topRight
uniform vec2 V0;    //bottomLeft
uniform vec2 V1;    //bottomRight

varying vec2 uv;

vec2 mirror(vec2 tex) 
{
    if (mod(floor(tex.x), 2.) == 1.)
    {
        tex = vec2(ceil(tex.x) - tex.x, tex.y);
    }
    else if (mod(floor(tex.x), 2.) == 0.)
    {
        tex = vec2(tex.x - floor(tex.x), tex.y);
    }

    if (mod(floor(tex.y), 2.) == 1.)
    {
        tex = vec2(tex.x, ceil(tex.y) - tex.y);
    }
    else if (mod(floor(tex.y), 2.) == 0.)
    {
        tex = vec2(tex.x, tex.y - floor(tex.y));
    }
    return tex;
}

vec2 outputSize(int needMirror, vec2 inputUV)
{
    if (needMirror == 1)
    {
        return mirror(inputUV);
    }
    else
    {
        return mod(inputUV, vec2(1.0));
    }    
}

void main()
{
    vec2 v3 = V3 / uMainTexSize;
    vec2 v2 = V2 / uMainTexSize;
    vec2 v0 = V0 / uMainTexSize;
    vec2 v1 = V1 / uMainTexSize;

    float dx1 = v1.x - v2.x,  dy1 = v1.y - v2.y;
    float dx2 = v3.x - v2.x,  dy2 = v3.y - v2.y;
    float sx = v0.x - v1.x + v2.x - v3.x;
    float sy = v0.y - v1.y + v2.y - v3.y;
    float g = (sx * dy2 - dx2 * sy) / (dx1 * dy2 - dx2 * dy1);
    float h = (dx1 * sy - sx * dy1) / (dx1 * dy2 - dx2 * dy1);
    float a = v1.x - v0.x + g * v1.x;
    float b = v3.x - v0.x + h * v3.x;
    float c = v0.x;
    float d = v1.y - v0.y + g * v1.y;
    float e = v3.y - v0.y + h * v3.y;
    float f = v0.y;

    float x = ((uv.x - c) * (e - h * uv.y) - (uv.y - f) * (b - h * uv.x)) / ((a - g * uv.x) * (e - h * uv.y) - (d - g * uv.y) * (b - h * uv.x));
    float y = ((uv.x - c) * (d - g * uv.y) - (uv.y - f) * (a - g * uv.x)) / ((b - h * uv.x) * (d - g * uv.y) - (e - h * uv.y) * (a - g * uv.x));

    gl_FragColor = texture2D(inputImageTexture, outputSize(flip, vec2(x, y)));     
}
]]

cornerPinAndTile = {}

function cornerPinAndTile:matchWithId(effectId)
    return 'KFM KSkr cornerPinAndTile' == effectId
end

function cornerPinAndTile.createWithId(effectId)
    if not cornerPinAndTile:matchWithId(effectId) then
        return nil
    end
    local o = {
        program = {},
        vertexBuffer = 0
    }
    o = newObject(o, cornerPinAndTile)
    o:init()
    return o;
end

function cornerPinAndTile:init()
    local buffer = {}
    glGenBuffers(1, buffer)
    self.vertexBuffer=buffer[1]

    local vertexBufferData = CGE.FloatBuffer:alloc(8)
    vertexBufferData:put(8, { -1, -1, 1, -1, -1, 1, 1, 1}, 0)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glBufferData(GL_ARRAY_BUFFER, 8, vertexBufferData, GL_STATIC_DRAW)

    self.program = CGE.ProgramObject()
    self.program:bindAttribLocation("vPosition", 0)
    self.program:initWithShaderStrings(s_vsh, s_fsh)
end

function cornerPinAndTile:onDestroy()
    glDeleteBuffers(1, {self.vertexBuffer})
end

function cornerPinAndTile:valueType(index)
    if index == 1 then
        --strength
        return FM.AEValueType_OneDInt
    elseif index == 2 then
        return FM.AEValueType_TwoD
    elseif index == 3 then
        return FM.AEValueType_TwoD
    elseif index == 4 then
        return FM.AEValueType_TwoD
    elseif index == 5 then
        return FM.AEValueType_TwoD
    end
end

function cornerPinAndTile:updateValue(index, val1, val2, val3)
    self.program:bind()
    if index == 1 then
        --strength        
        self.program:sendUniformi("flip", val1)
    elseif index == 2 then
        -- topLeft
        self.program:sendUniformf("V3", val1, val2)
    elseif index == 3 then
        -- topRight
        self.program:sendUniformf("V2", val1, val2)
    elseif index == 4 then
        -- bottomLeft
        self.program:sendUniformf("V0", val1, val2)
    elseif index == 5 then
        -- bottomright
        self.program:sendUniformf("V1", val1, val2)
    end
end

function cornerPinAndTile:resize(width, height)
    self.program:bind()
    self.program:sendUniformf("uMainTexSize", width, height)
end

function cornerPinAndTile:render(outFBO, inputTex)
    glBindFramebuffer(GL_FRAMEBUFFER, outFBO)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glEnableVertexAttribArray(0)
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, 0)
    glActiveTexture(GL_TEXTURE0)
    glBindTexture(GL_TEXTURE_2D, inputTex)
    self.program:bind()
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)
end
