---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by weijianwei.
--- DateTime: 2022/01/28
---

require ('script/ccsphere/mat4')

local function newObject(o, class)
    class.__index = class
    return setmetatable(o, class)
end

local s_vsh = [[
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif // GL_FRAGMENT_PRECISION_HIGH

attribute vec3 position;
attribute vec2 uv0;

uniform vec3 lightDirection;
uniform vec3 cameraPos;
uniform mat4 matWorld;
uniform mat4 matVP;
uniform mat4 matLH;
uniform mat4 matLD;
varying vec2 textureCoord;
varying vec3 worldNormal;
varying vec3 cameraDir;
varying vec3 lightDir;

void main()
{
    textureCoord = uv0;
    vec4 worldPosition = (matWorld * vec4(position, 1.0));
    lightDir = (matLD * matLH * vec4(lightDirection, 0.0)).xyz;
    cameraDir = worldPosition.xyz - cameraPos;
    worldNormal = (matWorld * vec4(position, 0.0)).xyz;
    gl_Position = matVP * worldPosition;
}
]]

local s_fsh = [[
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif // GL_FRAGMENT_PRECISION_HIGH

uniform float lightIntensity;
uniform vec3 lightColor;
uniform vec3 ambientColor;
uniform sampler2D inputImageTexture;
varying vec2 textureCoord;
varying vec3 worldNormal;
varying vec3 cameraDir;
varying vec3 lightDir;

void main() {
    vec4 texColor = texture2D(inputImageTexture, textureCoord);
    vec3 N = normalize(worldNormal);
    vec3 V = normalize(cameraDir);
    vec3 L = normalize(lightDir);
    vec3 H = normalize(V + L);
    float ndl = max(dot(N, L), 0.0);
    vec3 diffuse = texColor.rgb * ndl * lightColor * lightIntensity;
    float PI_DIV = 1.0 / 3.1415926;
	vec3 ambient = ambientColor * texColor.rgb;
    
	vec3 RLightDir = reflect(normalize(L), N);
	vec3 specular = pow(max(dot(RLightDir, V), 0.0), 32.0) * lightColor * lightIntensity * PI_DIV;

    gl_FragColor = vec4(diffuse + ambient + specular, texColor.a);
}
]]

CCSphere = {}

 local textureDrawer = nil
function CCSphere:matchWithId(effectId)
    return 'KFM KSkr CCSphere' == effectId
end

function CCSphere.createWithId(effectId)
    if not CCSphere:matchWithId(effectId) then
        return nil
    end
    local o = {
        shaderprogram = {},
        width = 0,
        height = 0,
        vertexBuffer = 0,
        uvBuffer = 0,
        indexBuffer = 0,
        indexCount = 0,
        pitch = 0,
        yaw = 0,
        roll = 0,
        radius = 200,
        lightHeight = 0,
        lightDegree = 0
    }
    o = newObject(o, CCSphere)
    o:init()
    return o;
end

function CCSphere:createShpere(longitude, latitude)
    local PI = math.pi
    local PI_2 = PI * 2.0
    local PI_DIV2 = PI * 0.5
    local angleLongitude
	local angleLatitude = -PI_DIV2
	local segmentLongitude = PI_2/longitude
	local segmentLatitude = PI/(latitude-1)
	local x, y, z, projectxz
    local vertices = {}
    local texcoords = {}
    local verIndex = 1
    local uvIndex = 1
    for i=0, latitude, 1 do
        angleLongitude = 0.0
        for j=0, longitude, 1 do
            y = self.radius * math.sin(angleLatitude)
            projectxz = self.radius * math.cos(angleLatitude)
            x = projectxz * math.cos(angleLongitude)
            z = projectxz * math.sin(angleLongitude)
            
            vertices[verIndex] = x
            verIndex = verIndex + 1
            vertices[verIndex] = y
            verIndex = verIndex + 1
            vertices[verIndex] = z
            verIndex = verIndex + 1

            texcoords[uvIndex] = 1.0 - j / longitude - 0.25
            uvIndex = uvIndex + 1
            texcoords[uvIndex] = i / latitude
            uvIndex = uvIndex + 1

            angleLongitude = angleLongitude + segmentLongitude
        end
        angleLatitude = angleLatitude + segmentLatitude;
    end

    local indices = {}
    local index = 1
    for i=0, latitude - 1, 1 do
        for j=0, longitude, 1 do
            if j == longitude - 1 then
                indices[index] = i * longitude + j
                index = index + 1
                indices[index] = (i + 1) * longitude + j
                index = index + 1
                indices[index] = (i + 1) * longitude
                index = index + 1
                indices[index] = i * longitude + j
                index = index + 1
                indices[index] = (i + 1) * longitude
                index = index + 1
                indices[index] = i * longitude
                index = index + 1
            else
                indices[index] = i * longitude + j
                index = index + 1
                indices[index] = (i + 1) * longitude + j
                index = index + 1
                indices[index] = (i + 1) * longitude + j + 1
                index = index + 1
                indices[index] = i * longitude + j
                index = index + 1
                indices[index] = (i + 1) * longitude + j + 1
                index = index + 1
                indices[index] = i * longitude + j + 1
                index = index + 1
            end
        end
    end
    self.indexCount = #indices

    glDeleteBuffers(3, {self.vertexBuffer, self.uvBuffer, self.indexBuffer})

    local buffer = {}
    glGenBuffers(3,buffer)
    self.vertexBuffer = buffer[1]
    self.uvBuffer = buffer[2]
    self.indexBuffer = buffer[3]

    local verticesData = CGE.FloatBuffer:alloc(#vertices)
    verticesData:put(#vertices, vertices, 0)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glBufferData(GL_ARRAY_BUFFER, #vertices, verticesData, GL_STATIC_DRAW)

    local uvData = CGE.FloatBuffer:alloc(#texcoords)
    uvData:put(#texcoords, texcoords, 0)
    glBindBuffer(GL_ARRAY_BUFFER, self.uvBuffer)
    glBufferData(GL_ARRAY_BUFFER, #texcoords, uvData, GL_STATIC_DRAW)

    local indicesData = CGE.ShortBuffer:alloc(#indices)
    indicesData:put(#indices, indices, 0)
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, self.indexBuffer)
    glBufferDataS(GL_ELEMENT_ARRAY_BUFFER, #indices, indicesData, GL_STATIC_DRAW)
end

function CCSphere:init()
    self:createShpere(32, 32)
    self.shaderprogram = CGE.ProgramObject()
    self.shaderprogram:bindAttribLocation('position', 0)
    self.shaderprogram:bindAttribLocation('uv0', 1)
    self.shaderprogram:initWithShaderStrings(s_vsh, s_fsh)
    self.shaderprogram:bind()
    self.shaderprogram:sendUniformi('inputImageTexture', 0)
    self.matVPLoc = self.shaderprogram:uniformLocation('matVP')
    self.matWorldLoc = self.shaderprogram:uniformLocation('matWorld')
    self.matLHLoc = self.shaderprogram:uniformLocation('matLH')
    self.matLDLoc = self.shaderprogram:uniformLocation('matLD')
end

function CCSphere:onDestroy()
    glDeleteBuffers(3, {self.vertexBuffer, self.uvBuffer, self.indexBuffer})
end

function CCSphere:MakeRotateMatrix(pitch, yaw, roll)
    local PI_180 = math.pi / 180.0
    local cx = math.cos(pitch * PI_180);
    local sx = math.sin(pitch * PI_180);
    local cy = math.cos(yaw * PI_180);
    local sy = math.sin(yaw * PI_180);
    local cz = math.cos(roll * PI_180);
    local sz = math.sin(roll * PI_180);
    local mat_table = {cy * cz, sx * sy * cz + cx * sz, -cx * sy * cz + sx * sz, 0.0,
                     -cy * sz, -sx * sy * sz + cx * cz, cx * sy * sz + sx * cz, 0.0,
                     sy, -sx * cy, cx * cy, 0.0,
                     0.0, 0.0, 0.0, 1.0 }
    return mat_table
end

function CCSphere:rotateAxis(lightDigree)
    local x = 0.0
    local y = 0.0
    local z = 1.0

    local radian = lightDigree * math.pi / 180.0
	local fSin = math.sin(radian);
	local fCos = math.cos(radian);
    local matrix = { 
		(x * x) * (1.0 - fCos) + fCos,
		(x * y) * (1.0 - fCos) + (z * fSin),
		(x * z) * (1.0 - fCos) - (y * fSin),
		0.0,

		(y * x) * (1.0 - fCos) - (z * fSin),
		(y * y) * (1.0 - fCos) + fCos,
		(y * z) * (1.0 - fCos) + (x * fSin),
		0.0,

		(z * x) * (1.0 - fCos) + (y * fSin),
		(z * y) * (1.0 - fCos) - (x * fSin),
		(z * z) * (1.0 - fCos) + fCos,
		0.0,

		0.0,
		0.0,
		0.0,
		1.0
        }
        return matrix
end

function CCSphere:makeLightDirection(lightHeight, lightDigree)
    local matrix1 = self:MakeRotateMatrix(-lightHeight * 3.6 * 0.25, 0, 0)
    local matrix2 = self:rotateAxis(lightDigree)
    self.shaderprogram:bind()
    self.shaderprogram:sendUniformf('lightDirection', 0, -1, 0)
    glUniformMatrix4fv(self.matLHLoc, 1, 0, matrix1)
    glUniformMatrix4fv(self.matLDLoc, 1, 0, matrix2)

end

function CCSphere:updateValue(index, val1, val2, val3)
    if index == 1 then
        self.pitch = val1
        local matrix = self:MakeRotateMatrix(math.modf(self.pitch, 100.0) * 3.6, math.modf(self.yaw, 100.0) * 3.6, math.modf(self.roll, 100.0) * 3.6)
        self.shaderprogram:bind()
        glUniformMatrix4fv(self.matWorldLoc, 1, 0, matrix)
    elseif index == 2 then
        self.yaw = val1
        local matrix = self:MakeRotateMatrix(math.modf(self.pitch, 100.0) * 3.6, math.modf(self.yaw, 100.0) * 3.6, math.modf(self.roll, 100.0) * 3.6)
        self.shaderprogram:bind()
        glUniformMatrix4fv(self.matWorldLoc, 1, 0, matrix)
    elseif index == 3 then
        self.roll = val1
        local matrix = self:MakeRotateMatrix(math.modf(self.pitch, 100.0) * 3.6, math.modf(self.yaw, 100.0) * 3.6, math.modf(self.roll, 100.0) * 3.6)
        self.shaderprogram:bind()
        glUniformMatrix4fv(self.matWorldLoc, 1, 0, matrix)
    elseif index == 4 then
        self.radius = val1
        self:createShpere(32, 32)
    elseif index ==5 then
        self.shaderprogram:bind()
        self.shaderprogram:sendUniformf('lightIntensity', val1 / 100)
    elseif index == 6 then
        self.lightHeight = val1
        self:makeLightDirection(self.lightHeight, self.lightDegree)
    elseif index == 7 then
        self.lightDigree = val1
        self:makeLightDirection(self.lightHeight, self.lightDegree)
    elseif index == 8 then
        self.shaderprogram:bind()
        self.shaderprogram:sendUniformf('lightColor', val1, val2, val3)
    elseif index == 9 then
        self.shaderprogram:bind()
        self.shaderprogram:sendUniformf('ambientColor', val1, val2, val3)
    end
end

function CCSphere:updateTimeAndFrame(time)
    
end

function CCSphere:resize(width, height)
    
end


function CCSphere:CustomResize(width, height)
    local fovy = math.pi / 3
    local proj = makePerspective(fovy, width/height, 0.1, 5000)

    local z = height/(math.tan(fovy/2)*2)
    local view = makeLookAt(ccsphere_vec3(0,0,z), ccsphere_vec3(0,0,0), ccsphere_vec3(0,1,0))

    proj = proj * view

    local proj_numTable = {proj.m00,proj.m01,proj.m02,proj.m03,
                           proj.m10,proj.m11,proj.m12,proj.m13,
                           proj.m20,proj.m21,proj.m22,proj.m23,
                           proj.m30,proj.m31,proj.m32,proj.m33}

    self.shaderprogram:bind()
    glUniformMatrix4fv(self.matVPLoc, 1, 0, proj_numTable)
    self.shaderprogram:sendUniformf('cameraPos', 0, 0, z)
end

function CCSphere:render(outFBO, inputTex)
    local viewportSize = {}
    glGetIntegerv(GL_VIEWPORT, 4, viewportSize)
    self:CustomResize(viewportSize[3], viewportSize[4])

    glEnable(GL_CULL_FACE);
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glEnableVertexAttribArray(0)
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 0, 0)

    glBindBuffer(GL_ARRAY_BUFFER, self.uvBuffer)
    glEnableVertexAttribArray(1)
    glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, 0, 0)

    glBindFramebuffer(GL_FRAMEBUFFER, outFBO)  
    glClearColor(0, 0, 0, 0)
    glClear(GL_COLOR_BUFFER_BIT)
    glActiveTexture(GL_TEXTURE0)
    glBindTexture(GL_TEXTURE_2D, inputTex)  
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
    self.shaderprogram:bind()
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, self.indexBuffer)
    glDrawElements(GL_TRIANGLES, self.indexCount, GL_UNSIGNED_SHORT, 0)

    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glBindBuffer(GL_ARRAY_BUFFER, 0)
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0)
    glDisableVertexAttribArray(1);
    glDisable(GL_CULL_FACE);
end