---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuzhenyang.
--- DateTime: 2020-06-16 19:01
---

local function newObject(o, class)
    class.__index = class
    return setmetatable(o, class)
end

local s_vsh = [[
attribute vec2 vPosition;
varying vec2 vUV0;
void main()
{
    gl_Position = vec4(vPosition, 0.0, 1.0);
    //An opportunism code. Do not use it unless you know what it means.
    vUV0 = (vPosition.xy + 1.0) / 2.0;
}
]]

local s_fsh = [[
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif

    uniform sampler2D inputImageTexture;
    uniform float uWarp;

    varying vec2 vUV0;

    void main()
    {

        vec2 center = vec2(0.5);
        float maxR = max(uWarp / 10.0 + 1.0, (1.0 -  uWarp / 10.0));

        vec2 uvLT = (vUV0 - center) / (vUV0.x * uWarp / 5.0 + 1.0) + center;
        uvLT = (uvLT - center) / (1.0 - (1.0 - vUV0.y) * uWarp / 5.0) + center;
        uvLT = (uvLT - center) / (1.0 / maxR) + center;

        vec2 uvRT = (vUV0 - center) / ((1.0 - vUV0.x) * uWarp / 5.0 + 1.0) + center;
        uvRT = (uvRT - center) / (1.0 - (1.0 - vUV0.y) * uWarp / 5.0) + center;
        uvRT = (uvRT - center) / (1.0 / maxR) + center;

        vec2 uvLB = (vUV0 - center) / (vUV0.x * uWarp / 5.0 + 1.0) + center;
        uvLB = (uvLB - center) / (1.0 - vUV0.y * uWarp / 5.0) + center;
        uvLB = (uvLB - center) / (1.0 / maxR) + center;

        vec2 uvRB = (vUV0 - center) / ((1.0 - vUV0.x) * uWarp / 5.0 + 1.0) + center;
        uvRB = (uvRB - center) / (1.0 - vUV0.y * uWarp / 5.0) + center;
        uvRB = (uvRB - center) / (1.0 / maxR) + center;

        if (uvLT.x > 0.0 && uvLT.x < .5 && uvLT.y > 0.5 && uvLT.y < 1.0)
        {
            gl_FragColor = texture2D(inputImageTexture, uvLT);
        }

        else if (uvRT.x > 0.5 && uvRT.x < 1.0 && uvRT.y > 0.5 && uvRT.y < 1.0)
        {
            gl_FragColor = texture2D(inputImageTexture, uvRT);
        }

        else if (uvLB.x > 0.0 && uvLB.x < .5 && uvLB.y > 0.0 && uvLB.y <= 0.5)
        {
            gl_FragColor = texture2D(inputImageTexture, uvLB);
        }

        else if (uvRB.x > 0.5 && uvRB.x < 1.0 && uvRB.y > 0.0 && uvRB.y <= 0.5)
        {
            gl_FragColor = texture2D(inputImageTexture, uvRB);
        }
        else
        {
            gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);
        }   
    }
]]

Fold = {}

function Fold:matchWithId(effectId)
    return 'KFM KSkr Fold' == effectId
end

function Fold.createWithId(effectId)
    if not Fold:matchWithId(effectId) then
        return nil
    end
    local o = {
        program = {},
        vertexBuffer = 0
    }
    o = newObject(o, Fold)
    o:init()
    return o;
end

function Fold:init()
    local buffer = {}
    glGenBuffers(1, buffer)
    self.vertexBuffer=buffer[1]

    local vertexBufferData = CGE.FloatBuffer:alloc(8)
    vertexBufferData:put(8, { -1, -1, 1, -1, -1, 1, 1, 1}, 0)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glBufferData(GL_ARRAY_BUFFER, 8, vertexBufferData, GL_STATIC_DRAW)

    self.program = CGE.ProgramObject()
    self.program:bindAttribLocation("vPosition", 0)
    self.program:initWithShaderStrings(s_vsh, s_fsh)
end

function Fold:updateTimeAndFrame(time)

end

function Fold:onDestroy()
    glDeleteBuffers(1, {self.vertexBuffer})
end

function Fold:valueType(index)
    if index == 1 then
        --strength
        return FM.AEValueType_OneDFloat
    end
end

function Fold:updateValue(index, val1, val2, val3)
    self.program:bind()
    if index == 1 then
        --strength        
        self.program:sendUniformf("uWarp", val1)
    end
end

function Fold:resize(width, height)

end

function Fold:render(outFBO, inputTex)
    glBindFramebuffer(GL_FRAMEBUFFER, outFBO)
    glBindBuffer(GL_ARRAY_BUFFER, self.vertexBuffer)
    glEnableVertexAttribArray(0)
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, 0)
    glActiveTexture(GL_TEXTURE0)
    glBindTexture(GL_TEXTURE_2D, inputTex)
    self.program:bind()
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)
end